site_name: GenAI Conference
site_url: https://mydomain.org/mysite
theme:
  name: material
  custom_dir: overrides
  logo: assets/delab_icon.png

  favicon: assets/delab_icon.png

  features:
    - navigation.instant
    - navigation.footer
    - header.autohide
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
 #   - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.tabs.sticky
    - toc.integrate
  
  language: en

  palette:
    scheme: delab
    accent: blue
  
  font:
    text: Open Sans
  
  hide:
    - toc

plugins:
  - tags

extra_css: 
  - extra.css


nav:
  - Home: "index.md"

markdown_extensions:
  - toc:
      title: Menu
  - pymdownx.details
  - admonition
  - pymdownx.superfences

extra:
  generator: true
  social:
    - icon: fontawesome/solid/d
      link: https://delab.uw.edu.pl/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/delabuw/mycompany/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/delabuw/?e=74fefe54-4de4-4c14-a4bd-c3e42ef26d65&g=5
    - icon: simple/youtube
      link: https://www.youtube.com/channel/UCuImpIgqCAqa-H0KMCJXfGw
    - icon: simple/x
      link: https://x.com/DELabUW
    - icon: simple/facebook
      link: https://www.facebook.com/DELabUW


