site_name: EDIH w DELab UW
site_url: https://mydomain.org/mysite
theme:
  name: material
  custom_dir: overrides
  logo: assets/wama_fav.png

  favicon: assets/wama.png

  features:
    - navigation.instant
    - navigation.footer
    - header.autohide
    - search.highlight 
    - search.share
    - search.suggest
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.tabs.sticky
    - toc.integrate


  footer: #FunduszeUE
  
  language: pl 

  palette:
    scheme: delab
    accent: blue
  
  font:
    text: Poppins
  
  hide:
    - toc

plugins:
  - tags
  - search
#  - frontmatter

extra_css: 
  - extra.css


nav:
  - O programie EDIH: "index.md"
  - FAQ: "faq.md"
  - Zespół: "zespol.md"
  - Kontakt: "kontakt.md"

markdown_extensions:
  - toc:
      title: Menu
  - pymdownx.details
  - admonition
  - pymdownx.superfences

extra:
  generator: true
  social:
    - icon: fontawesome/solid/d
      link: https://delab.uw.edu.pl/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/delabuw/mycompany/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/delabuw/?e=74fefe54-4de4-4c14-a4bd-c3e42ef26d65&g=5
    - icon: simple/youtube
      link: https://www.youtube.com/channel/UCuImpIgqCAqa-H0KMCJXfGw
    - icon: simple/x
      link: https://x.com/DELabUW
    - icon: simple/facebook
      link: https://www.facebook.com/DELabUW


copyright: |
  <span style="font-size: 150%; margin-bottom: 25px;"><b>#FunduszeUE</b></span>